### ISSUE TITLE
Creating new Scoring Function

### ISSUE THREAD

**Issue by sMattGuy** [Gildian/WikipediaGame#6]
As per @Gildian we should attempt a new scoring function.  
This scoring function would work as follows:
* Take a compound word (such as "house of cards") and calculate a midpoint between every word to get a new average tensor
* Do this to both the target word and the word being tested
* Use these two new tensors to calculate the cosine similarity
The idea is that this may return better results, due to a more accurate representation of compound words.  

**Please make sure to do this on a new branch**, do not work directly on main until it is verified to work.  
Please make sure that this only effects the scoring function, and all existing algorithms will be able to still use the same function (get_word_score)   

### Helpful links
[GloVe notes for distance](https://www.cs.toronto.edu/~lczhang/321/lec/glove_notes.html)
[GloVe notes for cosine similarity](https://www.cs.toronto.edu/~lczhang/aps360_20191/lec/w06/sentiment.html)

**Comment by Gildian** [comment]
Multi-word targets calculate the Euclidean distance between their vectors, and use that as the target vector. 

Additionally in this optimized version, the unit_split and target_split lists are created using list comprehensions that only include words that are in the glove dictionary. This reduces the number of lookups in the glove dictionary from len(target_split) * len(unit_split) to len(target_split) + len(unit_split).

Changes can be found in issue-6-multiword branch.
